### PR TITLE
remove dead link

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by toolmantim** [comment]
Thanks @efx!

@lukerollans where did it go? 🤷🏼‍♂️

**Comment by lukerollans** [comment]
Oh.. I don't know, I'll get it fixed up and open a new PR reverting this

**Comment by toolmantim** [comment]
@lukerollans alternatively, we'll just set it up in the Buildkite org so you're free to delete it. Happy to do that! I just need somewhere I can git clone it :)

**Comment by lukerollans** [comment]
That sounds more sustainable, I'll drop an address here shortly

**Pull request merged**
